version: '3'

services:
  app_dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_PORT=3000
    volumes:
      - .:/techrate
      - /techrate/node_modules
      - /data/certs:/etc/nginx/certs
    ports:
      - "3000:3000"
      - "443:443"
      - "8001:8001"
