version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/techrate
      - /techrate/node_modules
      - /data/certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
      - "8001:8001"
